### ISSUE TITLE
With list as input: Input vector should be 1-D

### ISSUE THREAD

**Issue by aldotapia** [oscarescuderoarnanz/dtwParallel#3]
The basic example fails:

```
from dtwParallel import dtw_functions
from scipy.spatial import distance as d

# For Univariate Time Series
x = [1,2,3]
y = [0,0,1]

dtw_functions.dtw(x,y,local_dissimilarity=d.euclidean)
```
Error message:
`ValueError: Input vector should be 1-D.`

Is this a bug or am I missing something?

**Comment by oscarescuderoarnanz** [comment]
Hi @aldotapia, I have tested the example on different machines, obtaining the result indicated in the README (5.0). The steps I followed were: 1) Make sure I had installed the latest version (0.9.35); 2) Open the anaconda environment and then a jupyter-notebook; 3) Run the attached example. Could you tell me more information about how you have carried out the execution of the example?
 
Thank you very much in advance.

**Comment by aldotapia** [comment]
Thanks for the support. I have the latest version installed. My python version is 3.10 for the environment I installed the library, and following your directions I used:

```shell
conda activate ee
jupyter-notebook
```

Then, in a new notebook:

```py
from dtwParallel import dtw_functions
from scipy.spatial import distance as d

# For Univariate Time Series
x = [1,2,3]
y = [0,0,1]

dtw_functions.dtw(x,y,local_dissimilarity=d.euclidean)
```

Same error message:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/t_/cbcq4k9d14l8g47hw5wpkrbw0000gn/T/ipykernel_60640/744360029.py in <cell line: 8>()
      6 y = [0,0,1]
      7 
----> 8 dtw_functions.dtw(x,y,local_dissimilarity=d.euclidean)

~/opt/anaconda3/envs/ee/lib/python3.10/site-packages/dtwParallel/dtw_functions.py in dtw(ts1, ts2, type_dtw, constrained_path_search, local_dissimilarity, MTS, get_visualization, check_errors, regular_flag, n_threads, dtw_to_kernel, sigma_kernel, itakura_max_slope, sakoe_chiba_radius, term_exec)
    512             # In case of having 2 UTS.
    513             else:
--> 514                 dtw_distance, cost_matrix = dtw_dep(ts1, ts2, local_dissimilarity, mask)
    515 
    516 

~/opt/anaconda3/envs/ee/lib/python3.10/site-packages/dtwParallel/dtw_functions.py in dtw_dep(ts1, ts2, local_dissimilarity, mask, mult_uts, regular_flag)
    367             for j in range(len_ts2):
    368                 if np.isfinite(mask[i, j]):
--> 369                     cost_matrix[i + 1, j + 1] = local_dissimilarity(ts1[i], ts2[j])
    370                     cost_matrix[i + 1, j + 1] += min(cost_matrix[i, j + 1],
    371                                            cost_matrix[i + 1, j],

~/opt/anaconda3/envs/ee/lib/python3.10/site-packages/scipy/spatial/distance.py in euclidean(u, v, w)
    516 
    517     """
--> 518     return minkowski(u, v, p=2, w=w)
    519 
    520 

~/opt/anaconda3/envs/ee/lib/python3.10/site-packages/scipy/spatial/distance.py in minkowski(u, v, p, w)
    459 
    460     """
--> 461     u = _validate_vector(u)
    462     v = _validate_vector(v)
    463     if p <= 0:

~/opt/anaconda3/envs/ee/lib/python3.10/site-packages/scipy/spatial/distance.py in _validate_vector(u, dtype)
    299     if u.ndim == 1:
    300         return u
--> 301     raise ValueError("Input vector should be 1-D.")
    302 
    303 

ValueError: Input vector should be 1-D.
```

I will create a fresh new environment and test it again

**Comment by aldotapia** [comment]
Sadly, same history (downgrading to python 3.9). I used these commands for creating my new env:

```bash
conda create -n dtwtest python=3.9
conda activate dtwtest
conda install -c conda-forge numpy pandas matplotlib seaborn setuptools scipy joblib numba
pip install gower
pip install notebook
pip install dtwParallel
```

And the test:

```
(dtwtest) aldotapia@MacBook-Aldo ~ % python
Python 3.9.15 (main, Nov 24 2022, 08:29:02) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from dtwParallel import dtw_functions
>>> from scipy.spatial import distance as d
>>> 
>>> # For Univariate Time Series
>>> x = [1,2,3]
>>> y = [0,0,1]
>>> 
>>> dtw_functions.dtw(x,y,local_dissimilarity=d.euclidean)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aldotapia/miniforge3/envs/dtwtest/lib/python3.9/site-packages/dtwParallel/dtw_functions.py", line 514, in dtw
    dtw_distance, cost_matrix = dtw_dep(ts1, ts2, local_dissimilarity, mask)
  File "/Users/aldotapia/miniforge3/envs/dtwtest/lib/python3.9/site-packages/dtwParallel/dtw_functions.py", line 369, in dtw_dep
    cost_matrix[i + 1, j + 1] = local_dissimilarity(ts1[i], ts2[j])
  File "/Users/aldotapia/miniforge3/envs/dtwtest/lib/python3.9/site-packages/scipy/spatial/distance.py", line 520, in euclidean
    return minkowski(u, v, p=2, w=w)
  File "/Users/aldotapia/miniforge3/envs/dtwtest/lib/python3.9/site-packages/scipy/spatial/distance.py", line 463, in minkowski
    u = _validate_vector(u)
  File "/Users/aldotapia/miniforge3/envs/dtwtest/lib/python3.9/site-packages/scipy/spatial/distance.py", line 302, in _validate_vector
    raise ValueError("Input vector should be 1-D.")
ValueError: Input vector should be 1-D.
```

**Comment by aldotapia** [comment]
Also, the dimensions are fine:

```
from dtwParallel import dtw_functions
from scipy.spatial import distance as d
import numpy as np

# For Univariate Time Series
x = np.array([1,2,3])
y = np.array([0,0,1])

print(x.ndim)
print(y.ndim)

dtw_functions.dtw(x,y,local_dissimilarity=d.euclidean)
```

```
1
1
ValueError: Input vector should be 1-D.
```

The error comes from scipy, not from dtwParallel. Odd that happens only in my laptop

**Comment by oscarescuderoarnanz** [comment]
Hi @aldotapia, I have indicated in the requirements.txt file the specific range of versions of scipy for which we know the program should work. I have created a new version (0.9.37). Could you please test it and tell me if the issue has been solved?

Thank you very much in advance.

**Comment by aldotapia** [comment]
Amazing, it solved the issue. Thank you so much for your help and for developing this package!
```
>>> from dtwParallel import dtw_functions
>>> from scipy.spatial import distance as d
>>> 
>>> # For Univariate Time Series
>>> x = [1,2,3]
>>> y = [0,0,1]
>>> 
>>> dtw_functions.dtw(x,y,local_dissimilarity=d.euclidean)
5.0
```
